apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - test-skaffold.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: test-skaffold
  path: flask.yaml

